language: c

compiler:
  - gcc
  - clang
  - musl-gcc

before_script:
  - sudo add-apt-repository ppa:bortis/ppa -y
  - sudo apt-get update -y
  - sudo apt-get install musl -y
  - sudo apt-get install musl-dev -y
  - ./buildrump.sh checkout

env:
  - LIBTYPE='MKPIC=no' DEBUG=''
  - LIBTYPE='MKSTATICLIB=no' DEBUG=''
  - LIBTYPE='MKSTATICLIB=no' DEBUG='-DDD'

script:
  -  dirsuf=${LIBTYPE}.${DEBUG}
  -  ./buildrump.sh -o obj.${dirsuf} -d rump.${dirsuf} -qq -j16 \
       -V ${LIBTYPE} ${DEBUG} fullbuild tests

notifications:
  irc:
    channels:
      - "chat.freenode.net#rumpkernel-builds"
    template:
      - '%{repository}#%{build_number} (%{branch} - %{commit} : %{author}): %{message}'
    skip_join: true
    use_notice: true
