language: c

compiler:
  - gcc
  - clang

script:
  - ./buildrump.sh checkout
  - ./buildrump.sh -o obj.a -d rump.a -qq -j16 -V MKPIC=no fullbuild tests
  - ./buildrump.sh -o obj -d rump -qq -j16 -V MKSTATICLIB=no fullbuild tests
