language: c

compiler:
  - gcc
  - clang

script:
  - ./buildrump.sh checkout
  - ./buildrump.sh -o obj.static -d rump.static -qq -j16 -V MKPIC=no
  - ./buildrump.sh -o obj -d rump -qq -j16 -V MKSTATICLIB=no
