language: c

compiler:
  - gcc
  - clang

before_script: ./buildrump.sh checkout

env:
  - DIRSUF='a' LIBTYPE='MKPIC=no' DEBUG=''
  - DIRSUF='so' LIBTYPE='MKSTATICLIB=no' DEBUG=''
  - DIRSUF='so.dbg' LIBTYPE='MKSTATICLIB=no' DEBUG='-DDD'

script:
    ./buildrump.sh -o obj.${DIRSUF} -d rump.${DIRSUF} -qq -j16 \
        -V ${LIBTYPE} ${DEBUG} fullbuild tests
