language: c

compiler:
  - gcc
  - clang

before_script:
  - ./buildrump.sh checkout

env:
  - LIBTYPE='MKPIC=no' BUILDTYPE=''
  - LIBTYPE='MKSTATICLIB=no' BUILDTYPE=''
  - LIBTYPE='MKSTATICLIB=no' BUILDTYPE='-DDD'
  - LIBTYPE='MKSTATICLIB=no' BUILDTYPE='-r'

script:
  -  dirsuf=${LIBTYPE}.${BUILDTYPE}
  -  ./buildrump.sh -o obj.${dirsuf} -d rump.${dirsuf} -qq -j16 -V ${LIBTYPE} ${BUILDTYPE} fullbuild tests

notifications:
  irc:
    channels:
      - "chat.freenode.net#rumpkernel-builds"
    template:
      - '%{repository}#%{build_number} (%{branch} - %{commit} : %{author}): %{message}'
    skip_join: true
    use_notice: true
  email:
    recipients:
      - rumpkernel-builds@lists.sourceforge.net
    on_success: always
    on_failure: always
